// Update actions

export const UPDATE_RACE = 'UPDATE_RACE';
export const UPDATE_CHARACTER_CLASS = 'UPDATE_CHARACTER_CLASS';
export const UPDATE_ABILITIES = 'UPDATE_ABILITIES';

export const UPDATE_BACKGROUND = 'UPDATE_BACKGROUND';
export const UPDATE_PROFICIENCIES = 'UPDATE_PROFICIENCIES';
export const UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT';

// Reset / clear actions

export const CLEAR_RACE = 'CLEAR_RACE';
export const CLEAR_CHARACTER_CLASS = 'CLEAR_CHARACTER_CLASS';
export const CLEAR_ABILITIES = 'CLEAR_ABILITIES';

export const CLEAR_BACKGROUND = 'CLEAR_BACKGROUND';
export const CLEAR_EQUIPMENT = 'CLEAR_EQUIPMENT';
export const CLEAR_PROFICIENCIES = 'CLEAR_PROFICIENCIES';


export const RESET_CHARACTER = 'RESET_CHARACTER';
export const SET_CHARACTER = 'SET_CHARACTER';
