// Update actions

export const UPDATE_RACE = 'UPDATE_RACE';
export const UPDATE_SUBRACE = 'UPDATE_SUB_RACE';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const UPDATE_ABILITIES = 'UPDATE_ABILITIES';

export const UPDATE_BACKGROUND = 'UPDATE_BACKGROUND';
export const UPDATE_ALIGNMENT = 'UPDATE_ALIGNMENT';
export const UPDATE_LANGUAGES = 'UPDATE_LANGUAGES';

export const UPDATE_PROFICIENCIES = 'UPDATE_PROFICIENCIES';
export const UPDATE_SPELLS = 'UPDATE_SPELLS';

// Reset / clear actions

export const CLEAR_RACE = 'CLEAR_RACE';
export const CLEAR_SUBRACE = 'CLEAR_SUB_RACE';
export const CLEAR_CLASS = 'CLEAR_CLASS';
export const CLEAR_ABILITIES = 'CLEAR_ABILITIES';

export const CLEAR_BACKGROUND = 'CLEAR_BACKGROUND';
export const CLEAR_ALIGNMENT = 'CLEAR_ALIGNMENT';
export const CLEAR_LANGUAGES = 'CLEAR_LANGUAGES';

export const CLEAR_PROFICIENCIES = 'CLEAR_PROFICIENCIES';
export const CLEAR_SPELLS = 'CLEAR_SPELLS';
